name: Continuous Integration

on:
  push:
    branches:
      - master
      - 'feature*'
      - 'hotfix*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Crear archivo de credenciales
        run: echo -e "USERNAME=${{ secrets.USERNAME }}\nPASSWORD=${{ secrets.PASSWORD }}" > credentials.ini

      - name: Publicar archivo como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: credentials
          path: credentials.ini

      - name: Build docker image
        run: docker build -t devops_ws:latest -t devops_ws:$(date +%s) .

      - name: Listar contenido del directorio
        run: ls -la
